/*

	Práctica 2 - Llamada a procedimiento remoto
	Sistemas Concurrentes y Distribuidos - Curso 2022/23
	Luis Miguel Guirado Bautista - UGR

	Fichero del servidor

*/

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

numero *
calculo_sencillo_1_svc(operacion_sencilla arg1,  struct svc_req *rqstp)
{
	static numero  result;
	printf("calculo_sencillo_1_svc\n");
	printf("Calculando %g %c %g...\n", arg1.n1, arg1.opr, arg1.n2);

	switch (arg1.opr)
	{
	case '+':
		result = arg1.n1 + arg1.n2;
		break;
	case '-':
		result = arg1.n1 - arg1.n2;
		break;
	case '*':
		result = arg1.n1 * arg1.n2;
		break;
	case '/':
		result = arg1.n1 / arg1.n2;
		break;

	default:
		break;
	}

	printf("Petición finalizada --------------------\n");
	return &result;
}

numero *
calculo_cadena_2_svc(cadena_operaciones arg1,  struct svc_req *rqstp)
{
	static numero result;
	printf("calculo_cadena_2_svc\n");

	printf("Números (%d): ", arg1.nums.numeros_len);
	for (unsigned int i=0; i < arg1.nums.numeros_len; i++) {
		printf("%g ", arg1.nums.numeros_val[i]);
	}
	printf("Operadores (%d): ", arg1.oprs.operadores_len);
	for (unsigned int i=0; i < arg1.oprs.operadores_len; i++) {
		printf("\'%c\' ", arg1.oprs.operadores_val[i]);
	}
	printf("\n");

	numero aux = arg1.nums.numeros_val[0];
	result = aux;
	for (unsigned int i=0; i < arg1.oprs.operadores_len; i++) {
		numero siguiente = arg1.nums.numeros_val[i+1];
		switch (arg1.oprs.operadores_val[i]) {
			case '+':
				result += siguiente;
				printf("+ %g = %g\n", siguiente, result);
				break;
			case '-':
				result -= siguiente;
				printf("- %g = %g\n", siguiente, result);
				break;
			case '*':
				result *= siguiente;
				printf("* %g = %g\n", siguiente, result);
				break;
			case '/':
				result /= siguiente;
				printf("/ %g = %g\n", siguiente, result);
				break;
			default:
				break;
		};
	}

	printf("Petición finalizada --------------------\n");
	return &result;
}
