/*

	Práctica 2 - Llamada a procedimiento remoto
	Sistemas Concurrentes y Distribuidos - Curso 2022/23
	Luis Miguel Guirado Bautista - UGR

	Fichero del cliente

*/

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

void calculadora_1(char *host, operacion_sencilla op)
{
	CLIENT *clnt;
	numero *result_1;
	operacion_sencilla calculo_sencillo_1_arg1 = op;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, BASICO, "tcp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	result_1 = calculo_sencillo_1(calculo_sencillo_1_arg1, clnt);
	if (result_1 == (numero *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	printf("El resultado es: %g\n", *result_1);

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

void calculadora_2(char *host, cadena_operaciones cadena)
{
	CLIENT *clnt;
	numero *result_1;
	cadena_operaciones calculo_cadena_2_arg1 = cadena;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, CADENA, "tcp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	result_1 = calculo_cadena_2(calculo_cadena_2_arg1, clnt);
	if (result_1 == (numero *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	printf("El resultado es: %g\n", *result_1);

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 5 || argc % 2 == 0)
	{
		printf("Uso: %s <hostname> <operacion>\n", argv[0]);
		printf("<operacion> := <num_1> <op_1> <num_2> <op_2> <num_3> ... <op_m> <num_n>\n");
		exit(1);
	}

	host = argv[1];

	if (argc == 5)
	{
		// Version básica con lo mínimo
		operacion_sencilla op;
		op.n1 = atof(argv[2]);
		op.opr = argv[3][0];
		op.n2 = atof(argv[4]);
		calculadora_1(host, op);
	}
	else if (argc % 2 == 1)
	{
		// Inicializamos la cadena de operaciones
		cadena_operaciones cadena;

		// Estimamos el número de decimales y de operadores y reservamos memoria
		cadena.nums.numeros_len = argc / 2;
		cadena.oprs.operadores_len = cadena.nums.numeros_len - 1;
		cadena.nums.numeros_val = malloc(cadena.nums.numeros_len * sizeof(numero));
		cadena.oprs.operadores_val = malloc(cadena.oprs.operadores_len * sizeof(char));

		// Obtenemos los números
		for (unsigned int i = 0; i < cadena.nums.numeros_len; i++)
		{
			cadena.nums.numeros_val[i] = atof(argv[ 2 * ( i+1 ) ]);
			//printf("%g\n", cadena.nums.numeros_val[i]);
		}
		// Obtenemos los operadores
		for (unsigned int i = 0; i < cadena.oprs.operadores_len; i++)
		{
			cadena.oprs.operadores_val[i] = argv[ 3 + ( 2*i ) ][0];
			//printf("%c\n", cadena.oprs.operadores_val[i]);
		}

		// Llamamos al procedimiento
		calculadora_2(host, cadena);
	}

	exit(0);
}
