/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_numero (XDR *xdrs, numero *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_numeros (XDR *xdrs, numeros *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->numeros_val, (u_int *) &objp->numeros_len, ~0,
		sizeof (numero), (xdrproc_t) xdr_numero))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operadores (XDR *xdrs, operadores *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->operadores_val, (u_int *) &objp->operadores_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operacion_sencilla (XDR *xdrs, operacion_sencilla *objp)
{
	register int32_t *buf;

	 if (!xdr_numero (xdrs, &objp->n1))
		 return FALSE;
	 if (!xdr_numero (xdrs, &objp->n2))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->opr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cadena_operaciones (XDR *xdrs, cadena_operaciones *objp)
{
	register int32_t *buf;

	 if (!xdr_numeros (xdrs, &objp->nums))
		 return FALSE;
	 if (!xdr_operadores (xdrs, &objp->oprs))
		 return FALSE;
	return TRUE;
}
