/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

numero *
calculo_sencillo_1(operacion_sencilla arg1,  CLIENT *clnt)
{
	static numero clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CALCULO_SENCILLO,
		(xdrproc_t) xdr_operacion_sencilla, (caddr_t) &arg1,
		(xdrproc_t) xdr_numero, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

numero *
calculo_cadena_2(cadena_operaciones arg1,  CLIENT *clnt)
{
	static numero clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CALCULO_CADENA,
		(xdrproc_t) xdr_cadena_operaciones, (caddr_t) &arg1,
		(xdrproc_t) xdr_numero, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
