/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

ResultadoNumerico *
calcular_1(Operacion arg1,  CLIENT *clnt)
{
	static ResultadoNumerico clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CALCULAR,
		(xdrproc_t) xdr_Operacion, (caddr_t) &arg1,
		(xdrproc_t) xdr_ResultadoNumerico, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ResultadoVectorial *
calcular_2(OperacionVectorial arg1,  CLIENT *clnt)
{
	static ResultadoVectorial clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CALCULAR,
		(xdrproc_t) xdr_OperacionVectorial, (caddr_t) &arg1,
		(xdrproc_t) xdr_ResultadoVectorial, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ResultadoNumerico *
calcular_3(OperacionCompuesta arg1,  CLIENT *clnt)
{
	static ResultadoNumerico clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CALCULAR,
		(xdrproc_t) xdr_OperacionCompuesta, (caddr_t) &arg1,
		(xdrproc_t) xdr_ResultadoNumerico, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
