/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

ResultadoNumerico *
calcular_1_svc(Operacion op, struct svc_req *rqstp)
{
	static ResultadoNumerico result;
	// A veces, el codigo de error anterior
	// se transfiere a operaciones posteriores,
	// por muy correctas que sean
	result.errnum = 0;

	Numero *resultado = &result.ResultadoNumerico_u.resultado;

	// printf(" ----- SOLICITUD RECIBIDA ----- \n");
	// printf("Operando 1: %.2f\n", op.operando1);
	// printf("Operador  : %c\n", op.operador);
	// printf("Operando 2: %.2f\n", op.operando2);

	switch (op.operador)
	{
	case '+':
		// printf("Procesando suma\n");
		*resultado = op.operando1 + op.operando2;
		break;
	case '-':
		// printf("Procesando resta\n");
		*resultado = op.operando1 - op.operando2;
		break;
	case '*':
		// printf("Procesando multiplicacion\n");
		*resultado = op.operando1 * op.operando2;
		break;
	case '/':
		// printf("Procesando division\n");
		// No se puede dividir por cero
		if (op.operando2 == 0)
		{
			result.errnum = 1;
			break;
		}
		*resultado = op.operando1 / op.operando2;
		break;
	// El operando no es reconocido por el servidor
	default:
		// printf("Operando no reconocido\n");
		result.errnum = 2;
		break;
	}

	// printf("Resultado : %.2f\n", *resultado);
	// printf("Error code: %i\n", result.errnum);
	// printf(" ------------------------------ \n\n");
	return &result;
}

ResultadoVectorial *
calcular_2_svc(OperacionVectorial op, struct svc_req *rqstp)
{
	static ResultadoVectorial result;
	result.errnum = 0;

	Vector *vectorResultado = &result.ResultadoVectorial_u.resultado;
	vectorResultado->dim = op.vector1.dim;
	vectorResultado->valores.ValoresVector_len = op.vector1.dim;
	vectorResultado->valores.ValoresVector_val = malloc(vectorResultado->dim * sizeof(Numero));

	for (int i=0; i < vectorResultado->dim; i++) {
		Numero valor1 = op.vector1.valores.ValoresVector_val[i];
		Numero valor2 = op.vector2.valores.ValoresVector_val[i];
		Numero *resultado = &result.ResultadoVectorial_u.resultado.valores.ValoresVector_val[i];
		switch (op.operador) {
			case '+':
				*resultado = valor1 + valor2;
				break;
			case '-':
				*resultado = valor1 - valor2;
				break;
			case '*':
				*resultado = valor1 * valor2;
				break;
			default:
				result.errnum = 2;
				break;
		}
	}

	return &result;
}

ResultadoNumerico *
calcular_3_svc(OperacionCompuesta op, struct svc_req *rqstp)
{
	static ResultadoNumerico result;

	return &result;
}
