/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef float numero;

typedef struct {
	u_int numeros_len;
	numero *numeros_val;
} numeros;

typedef struct {
	u_int operadores_len;
	char *operadores_val;
} operadores;

struct operacion_sencilla {
	numero n1;
	numero n2;
	char opr;
};
typedef struct operacion_sencilla operacion_sencilla;

struct cadena_operaciones {
	numeros nums;
	operadores oprs;
};
typedef struct cadena_operaciones cadena_operaciones;

#define CALCULADORA 0x30042069
#define BASICO 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULO_SENCILLO 1
extern  numero * calculo_sencillo_1(operacion_sencilla , CLIENT *);
extern  numero * calculo_sencillo_1_svc(operacion_sencilla , struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULO_SENCILLO 1
extern  numero * calculo_sencillo_1();
extern  numero * calculo_sencillo_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */
#define CADENA 2

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULO_CADENA 1
extern  numero * calculo_cadena_2(cadena_operaciones , CLIENT *);
extern  numero * calculo_cadena_2_svc(cadena_operaciones , struct svc_req *);
extern int calculadora_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULO_CADENA 1
extern  numero * calculo_cadena_2();
extern  numero * calculo_cadena_2_svc();
extern int calculadora_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numero (XDR *, numero*);
extern  bool_t xdr_numeros (XDR *, numeros*);
extern  bool_t xdr_operadores (XDR *, operadores*);
extern  bool_t xdr_operacion_sencilla (XDR *, operacion_sencilla*);
extern  bool_t xdr_cadena_operaciones (XDR *, cadena_operaciones*);

#else /* K&R C */
extern bool_t xdr_numero ();
extern bool_t xdr_numeros ();
extern bool_t xdr_operadores ();
extern bool_t xdr_operacion_sencilla ();
extern bool_t xdr_cadena_operaciones ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
